# Generated by Django 4.2.18 on 2025-03-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterystatus',
            name='charging',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
