# Generated by Django 4.2.18 on 2025-03-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batterystatus_charging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterystatus',
            name='charging',
        ),
    ]
