# Generated by Django 5.1.7 on 2025-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
